used:
  餐桌_盖上保鲜盒_0003_combo005_r1.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-19-00-44
    at: '2026-09-17 19:01:12'
  餐桌_盖上保鲜盒_0001_combo015_r2.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-19-03-42
    at: '2026-09-17 19:04:30'
  餐桌_盖上保鲜盒_0007_combo011_r2.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-19-04-32
    at: '2026-09-17 19:05:03'
  餐桌_盖上保鲜盒_0002_combo007_r1.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-19-05-28
    at: '2026-09-17 19:05:43'
  餐桌_盖上保鲜盒_0004_combo009_r2.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-19-05-43
    at: '2026-09-17 19:05:56'
  餐桌_盖上保鲜盒_0006_combo018_r2.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-19-06-19
    at: '2026-09-17 19:06:33'
  餐桌_盖上保鲜盒_0008_combo012_r1.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-19-06-33
    at: '2026-09-17 19:06:49'
  餐桌_盖上保鲜盒_0005_combo011_r3.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-19-06-49
    at: '2026-09-17 19:07:03'
  餐桌_盖上保鲜盒_0010_combo017_r3.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-19-07-03
    at: '2026-09-17 19:07:17'

