used:
  餐桌_盖上保鲜盒_0010_combo017_r3.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-16-59-42
    at: '2026-09-17 17:00:21'
  餐桌_盖上保鲜盒_0007_combo011_r2.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-17-00-49
    at: '2026-09-17 17:01:18'
  餐桌_盖上保鲜盒_0005_combo011_r3.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-17-01-18
    at: '2026-09-17 17:01:44'
  餐桌_盖上保鲜盒_0006_combo018_r2.png:
    session: /home/baai/Projects/Embodied-Brain-Collect/data/session-test/2026-09-17-17-16-40
    at: '2026-09-17 17:17:02'
